version: "3"

services:
    db:
        image: postgres:12.3
        environment:
            - POSTGRES_DB=postgres
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
        ports:
            - "5432:5432"

    app:
        build:
            context: .
        ports:
            - "8000:8000"
        volumes:
            - ./:/home/app/llevame/
        command: sh -c "dockerize -wait tcp://db:5432 python app/manage.py runserver 0.0.0.0:8000"
        depends_on:
            - "db"

    front:
        image: node:latest
        ports:
            - "3000:3000"
        volumes:
            - ./:/home/llevame
        stdin_open: true
        working_dir: /home/llevame/web/llevame
        command: bash -c "npm install && npm start"
