version: "3"

services:
    db:
        image: postgres:12.3
        volumes:
            - ~/postgres/llevame/dumps:/var/backups
        environment:
            - POSTGRES_DB=postgres
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres

    app:
        build:
            context: .
        ports:
            - "8000:8000"
        volumes:
            - ./app:/app
        command: sh -c "dockerize -wait tcp://db:5432 python manage.py runserver 0.0.0.0:8000"
        depends_on:
            - "db"
