# Generated by Django 3.0.7 on 2020-06-18 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='score',
            field=models.DecimalField(decimal_places=0, max_digits=1),
        ),
    ]
